Cargo.lock, src/lib.rs
The MLE5Large model URL doesn't follow the same naming convention as the other models
So, we tranform "fast-multilingual-e5-large" -> "intfloat-multilingual-e5-large" in the download URL
The model directory name in the GCS storage is "fast-multilingual-e5-large", like the others
=> fix: MLE5 large url transform

Cargo.lock, README.md, src/lib.rs
Adds supports for models introduced in https://github.com/qdrant/fastembed/pull/27, https://github.com/qdrant/fastembed/pull/25.
=> feat: New FlagEmbedding models

src/lib.rs
Right now the tokenizer is private, so it can't be used to count the number of tokens in a passage or to chunk passages to a specific token limit.
This PR moves towards resolving that.
=> feat: Allow tokenizer to be used to count tokens and limit tokens

Cargo.toml, src/lib.rs
=> refactor: impl Display for EmbeddingModel

src/lib.rs
Libraries shouldn't commit an environment themselves as it would be impossible or inconvenient to provide environment options, and since only one environment is allowed in a program at a time, an environment should only ever be committed once.
If an environment is not committed by the time a session is created, a default one will be created, so there is no need for `fastembed` to commit its own environment here.
=> fix: do not commit an environment on each model create

.github/workflows/test.yml, .releaserc, Cargo.lock, Cargo.toml
Updates `ort` to v2.0.0-rc.0.
Also gates enabling `ort`'s `download-binaries` feature behind a (default) feature, which can now be disabled in case the user doesn't want to use downloaded binaries.
=> chore: update ort to 2.0.0-rc.0

Cargo.toml, src/lib.rs
This fixes #30. Previously, an attempt to access a model while offline would fail, even if that model was already cached. This is because a request was made to the remote hugging face repo to obtain the file path of the .onnx model. This change implements a fallback search over the cache dir to find the relevant model file. It there are multiple snapshots for a particular model, it would not know which is the 'correct' file - this is unlikely to be a significant problem as this is only intended to be a fallback for DX purposes.
Also exposes new public function "get_model_info" - this is primarily to give users a convenient way of accessing model dimensions.
=> fix: full offline model retrieval (from cache)

README.md, src/lib.rs
This PR adds intfloat/multilingual-e5-base, -small models. 
these models have no "token_type_ids" inputs, so I introduce check logic.
curiously, intfloat/multilingual-e5-large onnx model is only 546kB(small is 470MB, base is 1.11GB). and it can't run inference. so, I commented out for large model definition.
=> add Multilingual E5 models

README.md, src/models/reranking.rs, tests/jinaai_multiligual.rs
This PR adds the Jina reranker v2 model, along with test code for this model.
=> feat: add jinaai-reranker-v2-base-multiligual

src/common.rs, src/lib.rs
The error type is exposed in the public API (for example, by the return type of `load_tokenizer`) but right now I can't refer to it without adding a dependency on `anyhow` myself.
=> chore: Export error type

README.md, src/models/sparse.rs, src/tests.rs
I made an oopsie. `is_sign_positive` also accounts for `+0.00`, which is incorrect and resulted in max size (30522) vectors. This fixes the issue.
=> fix: Splade sparse vectors should exclude zeros

src/lib.rs
This is so that consumer can initialise user defined mode. My bad, this should have gone into the previous PR.
=> patch: expose Pooling config

src/lib.rs, src/models/mod.rs, src/models/quantization.rs, src/models/text_embedding.rs, src/tests.rs, src/text_embedding/init.rs, src/text_embedding/models.rs, tests/optimum_cli_export.rs
Closes #107, at least as the short term solution.
`EmbeddingModel` now has a `get_quantization_mode` method which will return static values for the models behaviour. Not all quantized models are affected, thus we need to tell apart the non-quantized, static quantized and dynamic quantized.
Batch size will then be checked upon `transform` to see if the batch size is appropriate; if not, returns an `Err` stating the reason for it.
Also contains a minor refactor of `text_embedding.rs`, bringing the `models_list` into static scope, not requiring repeated instantiation every time `models_list` is called. This is done via `std::sync::OnceLock`. Also provides a convenient function `get_model_info`, which is an `O(1)` lookup with no memory cost to get the correct model if exists.
`cargo test …
=> fix!: Throws an informative error upon inappropriate batch size with Dynamic Quantized models

Cargo.toml, src/image_embedding/utils.rs
https://github.com/pykeio/ort/commit/92541cddcbcb21e28fe9466162b0f2fc7ae017ba
To hopefully fix https://github.com/Anush008/fastembed-rs/actions/runs/10442994580/job/28915920144
=> chore: bump ort to =2.0.0-rc.5

Cargo.toml, README.md, src/lib.rs, src/models/reranking.rs, src/reranking/impl.rs, src/reranking/init.rs, tests/embeddings.rs
This PR introduces support for the BGE Reranker V2 M3 model and enhances the flexibility of user-defined reranking models. Key changes include:
1. Added `BGERerankerV2M3` to the `RerankerModel` enum, supporting the "bge-reranker-v2-m3" model.
2. Introduced `OnnxSource` enum to allow loading ONNX models from either memory or file:
- `OnnxSource::Memory(Vec<u8>)`
- `OnnxSource::File(PathBuf)`
3. Updated `UserDefinedRerankingModel` to use `OnnxSource` instead of `Vec<u8>` for ONNX data.
4. Modified `TextRerank::try_new_from_user_defined()` to handle both memory and file-based ONNX sources.
5. Added support for additional files in `RerankerModelInfo` to accommodate models with multiple files (e.g., BGE Reranker V2 M3).
6. Updated the reranking test to be more flexible with result ordering, as …
=> feat: Support for bge-reranker-v2-m3

.github/workflows/test.yml, Cargo.toml, src/image_embedding/impl.rs, src/image_embedding/init.rs, src/lib.rs, src/output/embedding_output.rs, src/reranking/impl.rs, src/reranking/init.rs, src/sparse_text_embedding/impl.rs, src/sparse_text_embedding/init.rs, src/text_embedding/impl.rs, src/text_embedding/init.rs, tests/embeddings.rs
Resolves https://github.com/pykeio/ort/issues/320
=> chore: Bump ort to v2.0.0-rc.9

README.md, src/models/text_embedding.rs, tests/embeddings.rs
Thanks for this great crate. To support text-to-image search, it is useful to have `ClipVitB32` text embedding, as this maps to the same vector space as the `ClipVitB32` image embedder.
Let me know if changes are needed to this pull request.
=> Adding ClipVitB32 model so text-to-image search is supported.

src/image_embedding/impl.rs, src/reranking/impl.rs, src/sparse_text_embedding/impl.rs, src/text_embedding/impl.rs
I'm using this library in a scenario where I want to ignore certain errors, e.g. I want my application to continue running if embedding an image fails. Currently, this library panics in such cases, making it awkward to recover; in my opinion, many of the present calls to panic or unwrap should really be errors passed onto the user of the library, especially in cases where functions already return a `Result`.
In places where I felt like I understood the code well enough to understand the effects of such a change, this PR removes calls to `panic` and `unwrap` and instead passes the error onto the user. The unwrap logic for texts was not edited the same way that I did for images, as I'm not aware to how text embedding can fail from withing the parallel iterator implementing the embedding. …
=> refactor: Turn most panics into recoverable errors

README.md, src/image_embedding/impl.rs, src/models/image_embedding.rs, tests/embeddings.rs
nomic-embed-vision-v1.5 image embeddings that shares the same embedding space as nomic-embed-text-v1.5
Includes a test that outputs the similarity matrix between image and text. First column is blue cat, second is red cat:
```
green cat: [0.07165963, 0.067335285]
blue cat: [0.09806663, 0.055019084]
red cat: [0.06977239, 0.10732647]
yellow cat: [0.07075872, 0.071573]
dog: [0.035324473, 0.020524085]
```
=> adds support for nomic-embed-vision-v1.5 image embeddings model

src/output/embedding_output.rs
=> refactor: Elide SingleBatchOutput lifetimes

.github/workflows/test.yml, Cargo.toml, src/common.rs, src/image_embedding/impl.rs, src/image_embedding/utils.rs, src/lib.rs, src/reranking/impl.rs, src/sparse_text_embedding/impl.rs, src/text_embedding/impl.rs, tests/embeddings.rs, tests/optimum_cli_export.rs
Due to adjustments in features for hf-hub 0.4, I have added `hf-hub-native-tls` and `hf-hub-rustls-tls` here, and mapped `online` to `hf-hub-native-tls`.
=> chore: Bump hf-hub to 0.4.1

README.md, src/models/text_embedding.rs, src/text_embedding/impl.rs, tests/embeddings.rs
This adds [ModernBERT-embed-large](https://huggingface.co/lightonai/modernbert-embed-large) to the roster of available models.
ModernBERT is an encoder-only base model that was released at the end of last year. The model itself cannot be used for embeddings but a finetuned `-embed-*` version can be.
=> Add modernbert-embed-large

.envrc, .gitignore, flake.lock, flake.nix, src/image_embedding/impl.rs
- Allow embedding images from their bytes (i.e. you don't have to dump to disk first)
- Add Nix flake for easier development (I can remove this if you prefer)
=> feat: allow embedding image bytes, Nix environment

src/image_embedding/utils.rs
- Added BITImageProcessor to support dinov2 model (https://huggingface.co/Xenova/dinov2-small). 
- It is a very light weight and efficient model which can be used on-device for image embedding.
The change has made as per the preprocessor_config file of the dinov2 model. As compared to the clip Image processor it uses three more function which are do_resize, convert_rgb and do_centercrop. So I added these three function and rest of the flow of the code is same for CLIP Image processor and BIT Image Processor.
=> feat: BITImageProcessor support for dinov2 model

src/models/image_embedding.rs, src/models/reranking.rs, src/models/sparse.rs, src/models/text_embedding.rs
Some trait implementations to construct any model enum from a string containing the model code.
=> feat: create models from model_code string

src/common.rs, src/image_embedding/init.rs, src/lib.rs, src/reranking/init.rs, src/sparse_text_embedding/init.rs, src/text_embedding/init.rs, tests/embeddings.rs, tests/optimum_cli_export.rs
Being able to defined `cache_dir` from a environment variable `FASTEMBED_CACHE_DIR` for convenience
=> feat: resolve cache dir from env var

.github/workflows/test.yml, Cargo.toml, README.md, src/common.rs, src/image_embedding/impl.rs, src/lib.rs, src/output/embedding_output.rs, src/reranking/impl.rs, src/sparse_text_embedding/impl.rs, src/text_embedding/impl.rs, tests/embeddings.rs
- Resolves #169 - Bump `ort` to `2.0.0-rc.10` with necessary refactors.
- Resolves #163 - Remove `read_file_to_bytes` with `std::fs::read`.
- Removed dependency on Rayon.
=> refactor!: Upated ort usage

.github/workflows/test.yml, src/output/embedding_output.rs, tests/embeddings.rs
Resolves https://github.com/Anush008/fastembed-rs/issues/171
=> fix: Fix nondeterministic output tensor selection

src/lib.rs, src/output/embedding_output.rs, src/text_embedding/output.rs
`BTreeMap` doesn't preserve the original order, but orders the entries by key.
To preserve the original order we need to use a simple Vec
Additionally, the change to `OnlyOne` doesn't appear to be correct, because the semantic output of CLIP-Vit32-B-Text is not matching the images if it checks for `len() == 1`
=> Fix ordering of the model outputs

src/image_embedding/init.rs, src/image_embedding/mod.rs, src/init.rs, src/lib.rs, src/models/image_embedding.rs, src/models/reranking.rs, src/models/sparse.rs, src/models/text_embedding.rs, src/output/embedding_output.rs, src/reranking/impl.rs, src/reranking/init.rs, src/reranking/mod.rs, src/sparse_text_embedding/impl.rs, src/sparse_text_embedding/init.rs, src/sparse_text_embedding/mod.rs, src/text_embedding/impl.rs, src/text_embedding/init.rs, src/text_embedding/mod.rs
I'm currently working on a `deadpool_fastembed` library, and I realize it could be simplified with some common structs and implementations. Later on, I might implement `serde` support behind a feature flag. Let me know what you think of this direction! ;)
=> refactor: create a common struct & impl for embeddings

src/models/image_embedding.rs, src/models/model_info.rs, src/models/sparse.rs, src/models/text_embedding.rs, src/output/output_precedence.rs, src/text_embedding/impl.rs, src/text_embedding/init.rs, tests/embeddings.rs
* add output_key field to ModelInfo and update models to include it.
=> feat: adding EmbeddingGemma300M model
